### PR TITLE
Handle deadline-exceeded exceptions, and delete build requests after …

### PR DESCRIPTION
**Pull request by bhearsum**
…Taskcluster exceptions that result in the BuildRequest being cancelled.

This turned out to be pretty simple, since handling deadline-exceeded is the same as handling user cancellation. The other important change here is that the bridge will now remove Tasks from its own DB after an exception from Taskcluster as long as the Build didn't start. This prevents the case where the Task is cancelled in TC, but the bridge spins on it forever (because it didn't get a Build Finished event from Buildbot). This should prevent some of the stuck Tasks we saw earlier this week.

### CODE REVIEW

**Comment by jonasfj** [comment]
Looks good to me... I'm not sure why this created stuck tasks (I know little of bb).

But, you might not want to rely these messages. We do deliver them (at-least once), but RabbitMQ isn't super reliable (mostly doing maintenance). For robustness you should handle `409`s from `reclaimTask` exactly the same was as you handle these notifications. Because after deadline-exceeded or cancellation you can be sure that `reclaimTask` will return 409 :)

Anyways, pulse is fairly reliable, and we definitely want this (so that we can cancel fast). The `reclaimTask` thing is only for robustness.

**Comment by bhearsum** [comment]
The stuck tasks happened because there was nothing in the bridge that took care of removing tasks that never started in Buildbot from the bridge database, which is what this fixes :).

It turns out that we already handle 409s from reclaimTask....kindof. We delete the Task from the bridge database (yay!) but we don't cancel the Build (boo!). May as well fix that here.

**Comment by bhearsum** [comment]
@jonasfj - any more thoughts on this? I'll be testing it in dev next week along with a few other things.

**Comment by jonasfj** [comment]
looks reasonable to me...

Basically you can be fairly sure to get the `reclaimTask` error for both canceled and deadline exceeded... It's sort of a slow but very robust fallback when handling pulse messages fails.
So handling it like this is solid.

**Pull request merged**
