### PR TITLE
temporarily deny restricted scopes unconditionally

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by rail** [comment]
:cry: :sob:

**Comment by djmitche** [comment]
(tests updated)

**Comment by djmitche** [comment]
rail does that count as r+?

**Comment by rail** [comment]
Yeah, I was just trying to express my emotions. No more release promotion scheduling. :(

**Comment by djmitche** [comment]
I think I can fix this in the next few days, so only for a little while

**Pull request merged**
